# Primary Transactional Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:agents_of_leap}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:n3u3d4!}
spring.datasource.driver-class-name=org.postgresql.Driver

# Warehouse Analytics Database
spring.datasource.warehouse.jdbc-url=jdbc:postgresql://${WAREHOUSE_DB_HOST:localhost}:${WAREHOUSE_DB_PORT:25432}/${WAREHOUSE_DB_NAME:test_db}
spring.datasource.warehouse.username=${WAREHOUSE_DB_USER:test}
spring.datasource.warehouse.password=${WAREHOUSE_DB_PASSWORD:test}
spring.datasource.warehouse.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

spring.jpa.hibernate.ddl-auto=validate
server.port=8084